### ISSUE TITLE
不支持查询ipv6地址，程序报错了。

### ISSUE THREAD

**Issue by jszjgqq** [tagphi/czdb_searcher_php#2]
以下是示例代码，直接把ip改成ipv6的地址，代码会报错。

以下是报错内容：
`PHP Fatal error:  Uncaught Exception: IP [240e::1] format error for 4 in /Users/qdd/lighttpd/www-root/local.com/aaa/czdb_searcher_php-1.0.2-stable/src/DbSearcher.php:259`

以下是示例代码，就改了 ipv6 地址 跟 key，key我用的自己的，不放上来了。
```
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Czdb\DbSearcher;

$dbSearcher = new DbSearcher("/path/to/your/database.czdb", "BTREE", "YourEncryptionKey");

//$ip = "8.8.8.8";
$ip = "240e::1";
$region = $dbSearcher->search($ip);

echo "搜索结果：\n";
print_r($region);

$dbSearcher->close();
```

**Comment by craigliu** [comment]
查询ipv6需要ipv6数据库文件，目前社区版只发布了ipv4数据库文件。发布ipv6时我们会在公众号发文
